name: restaurantesaas_design_system
description: El Design System oficial de RestauranteSaas que define la identidad visual y los componentes interactivos reutilizables de la plataforma.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
widgetbook_annotation: ^3.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook: ^3.7.1
  widgetbook_generator: ^3.1.1 
  build_runner: ^2.4.1 

flutter:
  uses-material-design: true
